### ISSUE TITLE
SimpleTemplate usage

### ISSUE THREAD

**Issue by nfn** [shinshin86/bottle-flash2#1]
Hi

Tried to use bottle-flash2 with SimpleTemplate without success.

Can you share an example?
I tested and it just outputs the cookie secret.

Thanks.

**Comment by shinshin86** [comment]
@nfn  Hello.
I'm sorry for the delay in replying.

Thanks for putting up the issue!
I've created a sample using SimpleTemplate Engine.
Please check it out in the repository here.

[shinshin86/bottle-flash-2-example-with-simple-template-engine](https://github.com/shinshin86/bottle-flash-2-example-with-simple-template-engine)

I haven't used the SimpleTemplate Engine much, so I may have written it in a way that is not common.
If so, please send me a comment or PR.

Thanks.

**Comment by shinshin86** [comment]
I'm closing the issue because I think I've resolved the issues here.
If you still have unresolved issues, please create the issue again.
Thanks!
